### ISSUE TITLE
Missing input-file for wikiextractor in "extract_lan.sh"-script

### ISSUE THREAD

**Issue by Clemens123** [Babelscape/crocodile#2]
Hi, I've tried to execute the `extract_lan.sh` script now, but it results in this error:
```
downloading wikipedia and wikidata dumps...
2022-01-25 16:29:34,692 - wikimapper.download - INFO - Downloading [https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-page.sql.gz] to [data/de/dewiki-latest-page.sql.gz]
2022-01-25 16:30:36,991 - wikimapper.download - INFO - Downloading [https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-page_props.sql.gz] to [data/de/dewiki-latest-page_props.sql.gz]
2022-01-25 16:30:55,206 - wikimapper.download - INFO - Downloading [https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-redirect.sql.gz] to [data/de/dewiki-latest-redirect.sql.gz]
Create wikidata database
2022-01-25 16:31:00,687 - wikimapper.processor - INFO - Creating index for [dewiki-latest] in [data/de/index_dewiki-latest.db]
2022-01-25 16:31:00,697 - wikimapper.processor - INFO - Parsing pages dump
2022-01-25 16:31:51,875 - wikimapper.processor - INFO - Creating database index on 'wikipedia_title'
2022-01-25 16:31:55,962 - wikimapper.processor - INFO - Parsing page properties dump
2022-01-25 16:32:22,760 - wikimapper.processor - INFO - Parsing redirects dump
2022-01-25 16:32:45,246 - wikimapper.processor - INFO - Creating database index on 'wikidata_id'
Extract abstracts
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/crocodile/wikiextractor/wikiextractor/WikiExtractor.py", line 656, in <module>
    main()
  File "/content/crocodile/wikiextractor/wikiextractor/WikiExtractor.py", line 652, in main
    args.compress, args.processes, args.escape_doc)
  File "/content/crocodile/wikiextractor/wikiextractor/WikiExtractor.py", line 297, in process_dump
    input = decode_open(input_file)
  File "/content/crocodile/wikiextractor/wikiextractor/WikiExtractor.py", line 277, in decode_open
    return bz2.open(filename, mode=mode, encoding=encoding)
  File "/usr/lib/python3.7/bz2.py", line 318, in open
    binary_file = BZ2File(filename, bz_mode, compresslevel=compresslevel)
  File "/usr/lib/python3.7/bz2.py", line 92, in __init__
    self._fp = _builtin_open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/de/dewiki-latest-pages-articles-multistream.xml.bz2'
```

As the output shows, wikimapper downloads 4 files into the `data/de/`-directory, but non of them is a zipped xml file :(
Any ideas?

**Comment by LittlePea13** [comment]
Hi, you have to manually add that file. As a quick fix, you can modify Wikimapper to download it for you.

In the download.py script:
https://github.com/jcklie/wikimapper/blob/fadecea085bfa11779e33e94b03a8dcdd2d045a7/wikimapper/download.py#L49-L51

Add the following line:
`    wikipedia_dump = dumpname + "-pages-articles-multistream.xml.bz2"`

Best,
Pere-Lluis.

**Comment by KIMDOKYOUNG** [comment]
Hi, I've tried to execute the extract_lan.sh script , but it results in same error.
I already add that line in the download.py script, but it doesn't work.
maybe need to add in another place??
